apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attachments-pvc
  namespace: thesis
  labels:
    app: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 # AWS EKS storage class
  resources:
    requests:
      storage: 5Gi
